//! JSON / CSV / C exporters.

use anyhow::Result;
use disasm_core::{
    analysis::{Analysis, Function},
    loader::{Binary, Section, Symbol},
    strings::FoundString,
};
use rayon::prelude::*;
use serde::Serialize;

#[derive(Serialize)]
struct FunctionOut<'a> {
    entry: u64,
    name: &'a str,
    size: u64,
    insns: usize,
    blocks: usize,
    edges: usize,
    cyclomatic: usize,
    calls: Vec<u64>,
    callers: Vec<u64>,
}

#[derive(Serialize)]
struct DbOut<'a> {
    format: String,
    arch: String,
    image_base: u64,
    entry_points: &'a [u64],
    sections: Vec<&'a Section>,
    symbols: &'a [Symbol],
    functions: Vec<FunctionOut<'a>>,
    strings: &'a [FoundString],
}

pub fn json(bin: &Binary, a: &Analysis) -> Result<String> {
    let functions = a
        .functions()
        .map(|f| FunctionOut {
            entry: f.entry,
            name: &f.name,
            size: f.size,
            insns: f.insn_count(),
            blocks: f.cfg.block_count(),
            edges: f.cfg.edge_count(),
            cyclomatic: f.cfg.cyclomatic_complexity(),
            calls: f.calls.iter().copied().collect(),
            callers: a.xrefs.refs_to(f.entry).iter().map(|x| x.from).collect(),
        })
        .collect();
    let db = DbOut {
        format: format!("{:?}", bin.format),
        arch: format!("{:?}", bin.arch),
        image_base: bin.image_base,
        entry_points: &bin.entry_points,
        sections: bin.memory.sections().collect(),
        symbols: &bin.symbols,
        functions,
        strings: &a.strings,
    };
    Ok(serde_json::to_string_pretty(&db)? + "\n")
}

pub fn csv(a: &Analysis) -> String {
    let mut s = String::from("address,name,size,insns,blocks,edges,cyclomatic,callers\n");
    for f in a.functions() {
        s += &format!(
            "{:#x},\"{}\",{},{},{},{},{},{}\n",
            f.entry,
            f.name.replace('"', "\"\""),
            f.size,
            f.insn_count(),
            f.cfg.block_count(),
            f.cfg.edge_count(),
            f.cfg.cyclomatic_complexity(),
            a.xrefs.refs_to(f.entry).len()
        );
    }
    s
}

/// Decompile one function, resolving callee names.
pub fn c_one(bin: &Binary, a: &Analysis, f: &Function) -> String {
    let mut s = decompiler::decompile(f, bin.arch).unwrap_or_else(|e| format!("// {}: {e}\n", f.name));
    for c in &f.calls {
        if let Some(cf) = a.function(*c) {
            s = s.replace(&format!("sub_{c:x}("), &format!("{}(", cf.name));
        }
    }
    s
}

/// Decompile every function in parallel.
pub fn c_all(bin: &Binary, a: &Analysis) -> String {
    let funcs: Vec<&Function> = a.functions().collect();
    let parts: Vec<String> = funcs.par_iter().map(|f| c_one(bin, a, f)).collect();
    let mut out = String::from("// Generated by rdisasm\n#include <stdint.h>\n\n");
    for p in parts {
        out += &p;
        out.push('\n');
    }
    out
}
